package dev.rambo.airposture

import android.content.Context
import android.os.CombinedVibration
import android.os.VibrationEffect
import android.os.VibratorManager

interface HapticSink {
    fun postureWarning()
}

/** Default: vibrate the Android phone with a distinctive double pulse. */
class PhoneHapticSink(context: Context) : HapticSink {
    private val manager = context.getSystemService(VibratorManager::class.java)

    override fun postureWarning() {
        val effect = VibrationEffect.createWaveform(
            longArrayOf(0, 130, 90, 130),
            intArrayOf(0, 190, 0, 220),
            -1,
        )
        manager.vibrate(CombinedVibration.createParallel(effect))
    }
}

/**
 * Experimental target for the Fitbit Air's own vibration motor.
 * Do not guess or hard-code a proprietary UUID/payload. Wire this only after
 * a write characteristic + payload is identified from traffic generated by
 * an official silent-alarm operation on a device you own.
 */
class AirHapticSink(
    private val sendVerifiedHapticCommand: (() -> Unit)? = null,
) : HapticSink {
    override fun postureWarning() {
        sendVerifiedHapticCommand?.invoke()
    }
}

/** Prefer Air haptic when verified; always keep phone vibration as fallback. */
class FallbackHapticSink(
    private val phone: HapticSink,
    private val air: HapticSink? = null,
) : HapticSink {
    override fun postureWarning() {
        if (air == null) phone.postureWarning() else {
            try {
                air.postureWarning()
            } catch (_: Throwable) {
                phone.postureWarning()
            }
        }
    }
}
